export interface DiscoveredSpot {
  id: string;
  name: string;
  country: string;
  region: "Asia" | "Europe" | "Americas" | "Africa" | "Oceania" | "Polar";
  category: "mountains" | "beaches" | "heritage" | "nature" | "aurora" | "culinary";
  tagline: string;
  weather: string;
  rating: string;
  badge: string;
  quote: string;
  author: string;
  imageUrl: string;
  vibeTags: string[];
}

export const WORLD_SPOTS_CATALOG: DiscoveredSpot[] = [
  // ASIA & MIDDLE EAST
  {
    id: "bali",
    name: "Bali & Nusa Penida",
    country: "Indonesia",
    region: "Asia",
    category: "beaches",
    tagline: "Ocean Cliffs, Coral Reefs & Beachfront Stays",
    weather: "28°C · Gentle Sea Breeze",
    rating: "4.97 ★",
    badge: "🏝️ Tropical Haven",
    quote: "“From surf spots to jungle villas in Ubud, the whole schedule flowed effortlessly.”",
    author: "Chloe & Liam, Bali Honeymoon",
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Cliff Sunsets", "Surf Spots", "Jungle Villas"],
  },
  {
    id: "kyoto",
    name: "Kyoto & Arashiyama",
    country: "Japan",
    region: "Asia",
    category: "heritage",
    tagline: "Golden Bamboo Groves, Zen Temples & Geisha Quarters",
    weather: "21°C · Crisp Autumn",
    rating: "4.98 ★",
    badge: "🍁 Zen Sanctuary",
    quote: "“The autonomous food scout found 400-year-old tea houses and quiet bamboo paths away from tourists.”",
    author: "Elena R., Tokyo Explorer",
    imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Zen Gardens", "Matcha Cafes", "Autumn Leaves"],
  },
  {
    id: "ladakh",
    name: "Ladakh & Pangong Tso",
    country: "India",
    region: "Asia",
    category: "mountains",
    tagline: "High Mountain Passes, Ancient Monasteries & Stargazing",
    weather: "12°C · Ultra Clear",
    rating: "4.96 ★",
    badge: "🌌 Stargazing Sanctuary",
    quote: "“Acclimatization buffer days and road status updates made the 18,000ft pass ride effortless.”",
    author: "Vikram S., Adventure Rider",
    imageUrl: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Turquoise Lakes", "Monasteries", "Milky Way"],
  },
  {
    id: "cappadocia",
    name: "Cappadocia & Göreme",
    country: "Turkey",
    region: "Asia",
    category: "nature",
    tagline: "Hot Air Balloon Sunrises & Fairy Chimney Cave Suites",
    weather: "19°C · Gentle Sun",
    rating: "4.99 ★",
    badge: "🎈 Sunrise Ballooning",
    quote: "“Waking up inside an authentic cave suite with 100 balloons floating above the fairy chimneys was pure magic.”",
    author: "Sophia T., Travel Photographer",
    imageUrl: "https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Fairy Chimneys", "Cave Hotels", "Balloons"],
  },
  {
    id: "petra",
    name: "Petra & Wadi Rum",
    country: "Jordan",
    region: "Asia",
    category: "heritage",
    tagline: "Rose-Red Nabataean City & Mars-Like Red Desert Domes",
    weather: "24°C · Golden Sun",
    rating: "4.98 ★",
    badge: "🏜️ 7 Wonders of World",
    quote: "“Walking the Siq at sunrise when the Treasury glows red is an experience that stays with you forever.”",
    author: "Tariq K., Desert Nomad",
    imageUrl: "https://images.unsplash.com/photo-1579606032834-a82f3493e970?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Ancient Sandstone", "Bedouin Stargazing", "Camel Treks"],
  },
  {
    id: "fuji",
    name: "Mount Fuji & Five Lakes",
    country: "Japan",
    region: "Asia",
    category: "mountains",
    tagline: "Snow-Capped Volcanic Apex & Mirror Lake Onsen",
    weather: "16°C · Crisp Mountain Air",
    rating: "4.97 ★",
    badge: "🗻 Sacred Volcano",
    quote: "“Soaking in a private outdoor cedar onsen with Mount Fuji reflecting on Lake Kawaguchi at sunrise.”",
    author: "Kenji M., Tokyo Native",
    imageUrl: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Onsen Baths", "Mirror Lakes", "Cherry Blossoms"],
  },
  {
    id: "halong",
    name: "Ha Long Bay & Lan Ha",
    country: "Vietnam",
    region: "Asia",
    category: "beaches",
    tagline: "Emerald Waters & 1,600 Towering Limestone Islets",
    weather: "25°C · Warm Mist",
    rating: "4.92 ★",
    badge: "🛶 Emerald Sea Kayak",
    quote: "“Overnight luxury junk cruise through secluded lagoons with zero commercial tourist noise.”",
    author: "Nguyen D., Explorer",
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Limestone Pillars", "Sea Caves", "Night Squid Fishing"],
  },
  {
    id: "rajaampat",
    name: "Raja Ampat Coral Atolls",
    country: "Indonesia",
    region: "Asia",
    category: "beaches",
    tagline: "Richest Marine Biodiversity on Earth & Untouched Cays",
    weather: "29°C · Tropical Clear",
    rating: "4.99 ★",
    badge: "🤿 Marine Crown Jewel",
    quote: "“Diving with manta rays in water so clear it felt like floating through air above neon coral gardens.”",
    author: "Maya L., Marine Biologist",
    imageUrl: "https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Manta Rays", "Overwater Huts", "Jungle Islets"],
  },
  {
    id: "alula",
    name: "AlUla & Hegra",
    country: "Saudi Arabia",
    region: "Asia",
    category: "heritage",
    tagline: "Monolithic Carved Tombs in Golden Desert Canyons",
    weather: "26°C · Desert Gold",
    rating: "4.96 ★",
    badge: "✨ Living Museum",
    quote: "“Dining under the Maraya mirrored hall reflecting desert canyons at twilight was utterly surreal.”",
    author: "Nasser A., Cultural Curator",
    imageUrl: "https://images.unsplash.com/photo-1578895101408-1a36b834405b?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Maraya Mirror", "Hegra Tombs", "Elephant Rock"],
  },
  {
    id: "bagan",
    name: "Bagan Ancient Temples",
    country: "Myanmar",
    region: "Asia",
    category: "heritage",
    tagline: "2,000 Buddhist Pagodas Across Sun-Drenched Plains",
    weather: "28°C · Golden Haze",
    rating: "4.94 ★",
    badge: "🛕 Ancient Plains",
    quote: "“E-biking between 11th-century stupas as the morning mist lifted across the Irrawaddy river basin.”",
    author: "Thant Z., Heritage Explorer",
    imageUrl: "https://images.unsplash.com/photo-1508672019048-805b876b67e2?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Sunrise Pagodas", "E-Bike Trails", "Lacquerware"],
  },
  {
    id: "tawang",
    name: "Tawang & Sela Pass",
    country: "India",
    region: "Asia",
    category: "mountains",
    tagline: "Himalayan Buddhist Monasteries & Frozen Glacial Valleys",
    weather: "9°C · Alpine Frost",
    rating: "4.94 ★",
    badge: "🏔️ Eastern Himalaya",
    quote: "“The permit coordinator handled our inner line papers in 10 minutes. Unreal frozen lake vistas!”",
    author: "Ananya M., Himalayan Voyager",
    imageUrl: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["10,000 Buddhas", "Frozen Lakes", "Prayer Flags"],
  },

  // EUROPE & MEDITERRANEAN
  {
    id: "alps",
    name: "Swiss Alps & Zermatt",
    country: "Switzerland",
    region: "Europe",
    category: "mountains",
    tagline: "Glacier Express & High Alpine Ridges under Matterhorn",
    weather: "14°C · Crisp Alpine",
    rating: "4.99 ★",
    badge: "🏔️ Alpine Royalty",
    quote: "“The mountain hut routes and train transfers connected with Swiss-watch precision.”",
    author: "Marc K., Alpine Trekker",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Matterhorn", "Fondue Chalets", "Glacier Trails"],
  },
  {
    id: "amalfi",
    name: "Amalfi Coast & Positano",
    country: "Italy",
    region: "Europe",
    category: "beaches",
    tagline: "Pastel Cliffside Villages & Azure Tyrrhenian Sea",
    weather: "26°C · Warm Mediterranean",
    rating: "4.97 ★",
    badge: "🍋 Lemon Groves & Cliffs",
    quote: "“Cruising the coastal roads by vintage Vespa and eating seafood pasta right over the water.”",
    author: "Isabella G., Coastline Lover",
    imageUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Cliffside Stays", "Limoncello", "Speedboat Charters"],
  },
  {
    id: "santorini",
    name: "Santorini & Oia",
    country: "Greece",
    region: "Europe",
    category: "beaches",
    tagline: "White-Washed Cycladic Domes & Caldera Sunset Lounges",
    weather: "27°C · Aegean Sunshine",
    rating: "4.98 ★",
    badge: "🇬🇷 Aegean Gold",
    quote: "“The infinity plunge pool looking out over the caldera during sunset is an unbeatable feeling.”",
    author: "Dimitri N., Island Voyager",
    imageUrl: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Blue Domes", "Caldera Sunset", "Cave Suites"],
  },
  {
    id: "lofoten",
    name: "Lofoten Islands & Tromsø",
    country: "Norway",
    region: "Europe",
    category: "aurora",
    tagline: "Northern Lights, Rorbuer Fishermen Cabins & Arctic Fjords",
    weather: "3°C · Aurora Dancing",
    rating: "4.99 ★",
    badge: "🌌 Aurora Borealis",
    quote: "“Green curtains of Northern Lights dancing right over our red wooden cabin by the Arctic fjord.”",
    author: "Astrid B., Aurora Chaser",
    imageUrl: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Northern Lights", "Arctic Cabins", "Fjord Kayaking"],
  },
  {
    id: "dolomites",
    name: "Dolomites & Seceda",
    country: "Italy",
    region: "Europe",
    category: "mountains",
    tagline: "Jagged Limestone Peaks, Alpine Meadows & Rifugio Feasts",
    weather: "16°C · Sunny Alpine",
    rating: "4.98 ★",
    badge: "⛰️ UNESCO Dolomites",
    quote: "“Watching the Alpenglow illuminate Tre Cime di Lavaredo at sunset while drinking local Lagrein wine.”",
    author: "Luca V., Mountain Guide",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Seceda Ridge", "Alpine Rifugios", "Via Ferrata"],
  },
  {
    id: "tuscany",
    name: "Tuscany & Val d'Orcia",
    country: "Italy",
    region: "Europe",
    category: "culinary",
    tagline: "Rolling Cypress Hills, Stone Agriturismi & Truffle Feasts",
    weather: "23°C · Golden Afternoon",
    rating: "4.96 ★",
    badge: "🍷 Wine & Agriturismo",
    quote: "“Private wine cellars in Montepulciano and farmhouse olive oil tastings overlooking rolling cypress hills.”",
    author: "Matteo & Sarah, Foodies",
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Brunello Wine", "Cypress Hills", "Handmade Pasta"],
  },
  {
    id: "skye",
    name: "Isle of Skye & Highlands",
    country: "Scotland",
    region: "Europe",
    category: "nature",
    tagline: "Fairy Pools, Quiraing Ridges & Ancient Coastal Castles",
    weather: "13°C · Misty Scottish Air",
    rating: "4.95 ★",
    badge: "🏰 Celtic Mystique",
    quote: "“Wild dramatic hiking with zero crowds, staying in cozy seaside stone crofts with peat fires.”",
    author: "Callum Mac., Highland Walker",
    imageUrl: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Quiraing", "Highland Single Malt", "Fairy Glens"],
  },
  {
    id: "lakecomo",
    name: "Lake Como & Bellagio",
    country: "Italy",
    region: "Europe",
    category: "beaches",
    tagline: "Grand Lakeside Villas, Water Taxis & Alpine Reflections",
    weather: "24°C · Crystal Water",
    rating: "4.95 ★",
    badge: "🚤 Belle Époque Villas",
    quote: "“Taking a classic Riva wooden boat across crystal water to private botanical gardens in Villa Balbianello.”",
    author: "Julian H., Riviera Specialist",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Riva Boats", "Lakeside Cafes", "Villa Gardens"],
  },
  {
    id: "dubrovnik",
    name: "Dubrovnik & Adriatic Coast",
    country: "Croatia",
    region: "Europe",
    category: "heritage",
    tagline: "Medieval Sea Walls, Red Roofs & Island Hopping",
    weather: "25°C · Adriatic Breeze",
    rating: "4.94 ★",
    badge: "🛡️ Pearl of Adriatic",
    quote: "“Walking the ancient 14th-century stone ramparts overlooking the sparkling sapphire Adriatic sea.”",
    author: "Luka P., Mediterranean Guide",
    imageUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Ancient Walls", "Cliff Bars", "Island Catamarans"],
  },
  {
    id: "faroe",
    name: "Faroe Islands & Kalsoy",
    country: "Denmark",
    region: "Europe",
    category: "nature",
    tagline: "Grass-Roofed Villages, Sea Cliffs & Cascading Waterfalls",
    weather: "11°C · Ocean Gale & Sun",
    rating: "4.97 ★",
    badge: "🌊 Untamed North Atlantic",
    quote: "“Hiking to Kallur Lighthouse perched on a razor-thin cliff drop straight into the roaring Atlantic ocean.”",
    author: "Einar O., Nordic Wanderer",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Sea Cliffs", "Grass Roofs", "Puffin Colonies"],
  },

  // AMERICAS & CARIBBEAN
  {
    id: "banff",
    name: "Banff & Lake Louise",
    country: "Canada",
    region: "Americas",
    category: "mountains",
    tagline: "Turquoise Glacial Lakes, Pine Forests & Grizzly Corridors",
    weather: "16°C · Crisp Pine Breeze",
    rating: "4.98 ★",
    badge: "🛶 Canadian Rockies",
    quote: "“Canoeing on Lake Moraine at 6 AM when the water looks like polished neon turquoise glass.”",
    author: "Dave C., Wilderness Canoeist",
    imageUrl: "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Lake Moraine", "Fairmont Chateau", "Icefields Parkway"],
  },
  {
    id: "patagonia",
    name: "Patagonia & Torres del Paine",
    country: "Chile & Argentina",
    region: "Americas",
    category: "mountains",
    tagline: "Granite Horns, Electric Blue Glaciers & Wild Guanacos",
    weather: "10°C · Clean Patagonian Wind",
    rating: "4.99 ★",
    badge: "🏔️ End of the Earth",
    quote: "“The W-Trek logistics and glamping domes right under the granite spires were completely dialed in.”",
    author: "Gabriel R., Expedition Leader",
    imageUrl: "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Grey Glacier", "Granite Towers", "Wild Gauchos"],
  },
  {
    id: "maui",
    name: "Maui & Na Pali Coast",
    country: "Hawaii, USA",
    region: "Americas",
    category: "beaches",
    tagline: "Emerald Sea Cliffs, Black Sand Beaches & Road to Hana",
    weather: "27°C · Tropical Sunshine",
    rating: "4.96 ★",
    badge: "🌺 Pacific Paradise",
    quote: "“Helicopter tour soaring over 3,000ft sheer emerald cliffs dropping directly into turquoise Pacific swells.”",
    author: "Kai K., Island Resident",
    imageUrl: "https://images.unsplash.com/photo-1542259009477-d625272157b7?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Hana Highway", "Haleakala Sunrise", "Sea Turtles"],
  },
  {
    id: "machupicchu",
    name: "Machu Picchu & Sacred Valley",
    country: "Peru",
    region: "Americas",
    category: "heritage",
    tagline: "Inca Citadels in the Clouds & Andean Farming Terraces",
    weather: "18°C · Mountain Mist",
    rating: "4.98 ★",
    badge: "🦙 Citadel in Clouds",
    quote: "“Seeing the sun break through morning cloud mist over the ancient ruins of Huayna Picchu gave me chills.”",
    author: "Lucia M., Andean Trekker",
    imageUrl: "https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Inca Trail", "Llamas", "Vistadome Train"],
  },
  {
    id: "tulum",
    name: "Tulum & Riviera Maya",
    country: "Mexico",
    region: "Americas",
    category: "beaches",
    tagline: "Mayan Ruins by Turquoise Caribbean & Secret Cenotes",
    weather: "29°C · Caribbean Sun",
    rating: "4.93 ★",
    badge: "🌊 Cenotes & Ruins",
    quote: "“Swimming in crystal clear subterranean cenotes illuminated by jungle sunlight beams.”",
    author: "Mateo S., Riviera Explorer",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Limestone Cenotes", "Beachfront Cabanas", "Taco Tours"],
  },
  {
    id: "uyuni",
    name: "Salar de Uyuni Salt Flats",
    country: "Bolivia",
    region: "Americas",
    category: "nature",
    tagline: "World's Largest Natural Mirror & Flamingos at Sunset",
    weather: "14°C · High Altitude Sun",
    rating: "4.98 ★",
    badge: "🪞 Infinite Mirror",
    quote: "“When the thin layer of water turns the 10,000 sq km salt desert into a giant mirror reflecting the starry sky.”",
    author: "Camila F., Altiplano Traveler",
    imageUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Salt Hotel", "Starlight Reflection", "Red Lagoon"],
  },

  // AFRICA & OCEANIA & POLAR
  {
    id: "serengeti",
    name: "Serengeti & Ngorongoro",
    country: "Tanzania",
    region: "Africa",
    category: "nature",
    tagline: "Great Wildlife Migration & White Sand Spice Islands",
    weather: "26°C · Savanna Sun",
    rating: "4.99 ★",
    badge: "🦁 Big Five Safari",
    quote: "“Witnessed the river crossing of 50,000 wildebeests, followed by 4 days in a water villa in Zanzibar.”",
    author: "Amara N., Safari Specialist",
    imageUrl: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Great Migration", "Luxury Tents", "Spice Island Stays"],
  },
  {
    id: "queenstown",
    name: "Queenstown & Milford Sound",
    country: "New Zealand",
    region: "Oceania",
    category: "mountains",
    tagline: "Lord of the Rings Fjords, Glaciers & Pure Alpine Thrills",
    weather: "15°C · Alpine Air",
    rating: "4.98 ★",
    badge: "🛶 Fiordland Wonder",
    quote: "“Cruising underneath Stirling Falls with hundreds of waterfalls cascading straight from sheer alpine cliffs.”",
    author: "Oliver W., Kiwi Adventurer",
    imageUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Milford Sound", "Lord of the Rings", "Jet Boating"],
  },
  {
    id: "sahara",
    name: "Sahara Dunes & Chefchaouen",
    country: "Morocco",
    region: "Africa",
    category: "heritage",
    tagline: "Golden Erg Chebbi Dunes & Blue Mountain Medinas",
    weather: "23°C · Desert Breeze",
    rating: "4.94 ★",
    badge: "🐪 Golden Sand Sea",
    quote: "“Luxury desert glamping under a billion stars after riding camels across the orange crest dunes.”",
    author: "Youssef B., Desert Guide",
    imageUrl: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Camel Caravans", "Blue City", "Riad Gardens"],
  },
  {
    id: "borabora",
    name: "Bora Bora & Tahiti",
    country: "French Polynesia",
    region: "Oceania",
    category: "beaches",
    tagline: "Overwater Bungalows & Mount Otemanu Turquoise Lagoon",
    weather: "29°C · Lagoon Breeze",
    rating: "4.99 ★",
    badge: "💎 Overwater Luxury",
    quote: "“Stepping straight from the king bed down a wooden ladder into warm turquoise coral gardens.”",
    author: "Claire & Thomas, Honeymooners",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Overwater Villas", "Manta Rays", "Mount Otemanu"],
  },
  {
    id: "iceland",
    name: "Reykjavik & Blue Lagoon",
    country: "Iceland",
    region: "Polar",
    category: "aurora",
    tagline: "Geothermal Lagoons, Black Sand Beaches & Glacial Caves",
    weather: "6°C · Crisp Volcanic",
    rating: "4.97 ★",
    badge: "🌋 Land of Fire & Ice",
    quote: "“Soaking in milky silica thermal waters while fresh snow falls on your shoulders under the twilight sky.”",
    author: "Bjorn H., Nordic Guide",
    imageUrl: "https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Silica Springs", "Black Sand Beaches", "Glacier Caves"],
  },
  {
    id: "capetown",
    name: "Cape Town & Table Mountain",
    country: "South Africa",
    region: "Africa",
    category: "nature",
    tagline: "Dramatic Oceanic Headlands, Penguin Coves & Winelands",
    weather: "24°C · Atlantic Sunshine",
    rating: "4.96 ★",
    badge: "🐧 Cape of Good Hope",
    quote: "“Sunset cable car down Table Mountain followed by fresh linefish at Camps Bay beach.”",
    author: "Sipho M., Local Host",
    imageUrl: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Table Mountain", "Boulders Penguins", "Stellenbosch"],
  },
  {
    id: "greatbarrier",
    name: "Great Barrier Reef & Whitsundays",
    country: "Australia",
    region: "Oceania",
    category: "beaches",
    tagline: "Silica Sand Whitehaven Beach & Coral Cays",
    weather: "28°C · Coral Sun",
    rating: "4.97 ★",
    badge: "🐠 Coral Wonder",
    quote: "“Flying over Heart Reef by seaplane and stepping onto Whitehaven Beach's pure white 98% silica sand.”",
    author: "Liam H., Queensland Sailor",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Whitehaven Beach", "Heart Reef", "Catamaran Cruise"],
  },
  {
    id: "lapland",
    name: "Lapland & Rovaniemi",
    country: "Finland",
    region: "Polar",
    category: "aurora",
    tagline: "Glass Igloos, Reindeer Sleighs & Arctic Taiga",
    weather: "-4°C · Arctic Starlight",
    rating: "4.98 ★",
    badge: "✨ Glass Igloo Village",
    quote: "“Sleeping in a heated 360-degree glass dome watching the green Aurora dance right above our bed.”",
    author: "Milla K., Taiga Guide",
    imageUrl: "https://images.unsplash.com/photo-1517411032315-54ef2cb783bb?auto=format&fit=crop&w=1200&q=80",
    vibeTags: ["Glass Igloos", "Husky Sledding", "Aurora Borealis"],
  }
];
