import type {
  Place,
  VideoAsset,
  ReviewIntel,
  HotelOption,
  FlightOption,
  TransportOption,
  Permit,
  FoodPick,
} from "../types";
import { img, imgSet, video } from "./media";

const now = () => new Date().toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 864e5).toISOString();

// ---------------------------------------------------------------------------
// VIDEOS
// ---------------------------------------------------------------------------
export const TAWANG_VIDEOS: VideoAsset[] = [
  video("place_bumla", "Driving to Bum La Pass", "Himalayan Roads", "14:22", "Shows the actual road journey and terrain above 15,000 ft.", "road"),
  video("place_monastery", "Inside Tawang Monastery", "Monastery Walks", "09:41", "A calm walkthrough of the courtyards and prayer hall.", "walk"),
  video("place_sela", "Sela Pass in early winter", "Ride East", "07:15", "Seasonal conditions and snow at the pass.", "seasonal"),
  video("place_madhuri", "Madhuri Lake (Sangetsar) visit", "Frame & Trail", "06:58", "What the lake actually looks like on arrival.", "attraction"),
  video("place_nuranang", "Nuranang Falls up close", "Frame & Trail", "04:33", "The approach and viewing point for the falls.", "attraction"),
  video("dest_tawang", "Tawang in 6 days — full vlog", "Slow Nomad", "22:10", "A realistic pace for the whole circuit.", "vlog"),
  video("hotel_h1", "Room tour — mountain-view stay", "StayScout", "05:12", "Actual room and bathroom condition.", "room_tour"),
  video("hotel_h1", "Guest review after 3 nights", "StayScout", "03:44", "Independent take on cleanliness and hot water.", "review"),
  video("food_f1", "Thukpa & momos in Tawang town", "Plate Wanderer", "08:05", "Local food spots and portions.", "food"),
];

// ---------------------------------------------------------------------------
// REVIEW INTEL
// ---------------------------------------------------------------------------
export const TAWANG_REVIEWS: Record<string, ReviewIntel> = {
  ri_h1: {
    entityId: "hotel_h1",
    overall: 4.3,
    count: 312,
    aspects: [
      { aspect: "Cleanliness", score: 9.0, mentions: 141 },
      { aspect: "Bathroom", score: 8.6, mentions: 88 },
      { aspect: "Hot water", score: 7.1, mentions: 62 },
      { aspect: "Bed", score: 8.4, mentions: 54 },
      { aspect: "Staff", score: 9.2, mentions: 96 },
      { aspect: "Noise", score: 7.0, mentions: 33 },
      { aspect: "Location", score: 8.8, mentions: 71 },
      { aspect: "Value", score: 8.1, mentions: 60 },
    ],
    positives: ["Clean rooms", "Helpful staff", "Great mountain views"],
    negatives: ["Inconsistent hot water", "Some rooms hear the street"],
    recentConcern: "3 recent reviews mention water pressure in the mornings.",
    trend: "stable",
  },
  ri_h2: {
    entityId: "hotel_h2",
    overall: 4.5,
    count: 208,
    aspects: [
      { aspect: "Cleanliness", score: 9.3, mentions: 120 },
      { aspect: "Bathroom", score: 9.0, mentions: 74 },
      { aspect: "Hot water", score: 8.6, mentions: 51 },
      { aspect: "Bed", score: 8.7, mentions: 40 },
      { aspect: "Staff", score: 8.9, mentions: 66 },
      { aspect: "Noise", score: 8.4, mentions: 22 },
      { aspect: "Location", score: 7.9, mentions: 44 },
      { aspect: "Value", score: 7.4, mentions: 38 },
    ],
    positives: ["Spotless bathrooms", "Reliable hot water", "Quiet"],
    negatives: ["Slightly further from the monastery", "Pricier"],
    trend: "improving",
  },
  ri_h3: {
    entityId: "hotel_h3",
    overall: 3.9,
    count: 156,
    aspects: [
      { aspect: "Cleanliness", score: 7.6, mentions: 70 },
      { aspect: "Bathroom", score: 6.8, mentions: 55 },
      { aspect: "Hot water", score: 6.2, mentions: 48 },
      { aspect: "Bed", score: 7.9, mentions: 30 },
      { aspect: "Staff", score: 8.1, mentions: 41 },
      { aspect: "Noise", score: 6.6, mentions: 28 },
      { aspect: "Location", score: 9.1, mentions: 60 },
      { aspect: "Value", score: 8.8, mentions: 52 },
    ],
    positives: ["Cheapest central option", "Great location", "Friendly owner"],
    negatives: ["Small bathrooms", "Hot water can be limited", "Thin walls"],
    recentConcern: "Multiple recent reviews mention small bathrooms.",
    trend: "declining",
  },
  ri_f1: {
    entityId: "food_f1",
    overall: 4.4,
    count: 96,
    aspects: [
      { aspect: "Food quality", score: 8.8, mentions: 60 },
      { aspect: "Price", score: 9.1, mentions: 40 },
      { aspect: "Service", score: 8.0, mentions: 28 },
      { aspect: "Cleanliness", score: 8.3, mentions: 22 },
    ],
    positives: ["Great thukpa", "Cheap", "Generous portions"],
    negatives: ["Can get crowded at lunch"],
    trend: "stable",
  },
};

// ---------------------------------------------------------------------------
// PLACES
// ---------------------------------------------------------------------------
export const TAWANG_PLACES: Place[] = [
  {
    id: "place_monastery",
    canonicalName: "Tawang Monastery",
    altNames: ["Tawang Gompa", "Tawang Gaden Namgyal Lhatse"],
    category: "core",
    blurb: "The largest monastery in India and the spiritual heart of Tawang.",
    description:
      "Founded in the 17th century, Tawang Monastery sits above the town at roughly 3,000 m. Its golden-roofed prayer hall, resident monks and sweeping valley views make it the defining sight of the region.",
    images: [img("monastery", "attraction"), img("monastery", "attraction"), img("town", "guest", "guest")],
    videoIds: ["vid_2"],
    durationHours: 2.5,
    distanceKm: 2,
    travelTime: "10 min",
    bestTime: "Early morning for prayers",
    difficulty: "easy",
    accessible: "partial",
    permitRequired: false,
    facts: ["Largest monastery in India", "~450 monks in residence", "Founded c. 1680"],
    nearby: ["place_urgelling", "place_buddha"],
    sourceIds: ["ap_tourism", "publication", "review_platform"],
    confidence: 0.92,
    routeOrder: 10,
  },
  {
    id: "place_buddha",
    canonicalName: "Giant Buddha Statue",
    altNames: ["Tawang Buddha", "Buddha Park"],
    category: "core",
    blurb: "A serene hilltop Buddha overlooking Tawang town.",
    description:
      "A large gilded Buddha statue on a ridge with panoramic town views — a short, easy stop that pairs well with sunset.",
    images: imgSet("buddha", "attraction", 2),
    videoIds: [],
    durationHours: 0.75,
    distanceKm: 3,
    travelTime: "12 min",
    bestTime: "Golden hour",
    difficulty: "easy",
    accessible: "yes",
    permitRequired: false,
    facts: ["Panoramic town views", "Popular sunset spot"],
    nearby: ["place_monastery"],
    sourceIds: ["ap_tourism", "blog"],
    confidence: 0.85,
    routeOrder: 11,
  },
  {
    id: "place_urgelling",
    canonicalName: "Urgelling Monastery",
    altNames: ["Urgyelling"],
    category: "core",
    blurb: "Birthplace of the 6th Dalai Lama, quiet and historic.",
    description:
      "A small, atmospheric monastery below the town, historically significant as the birthplace of the 6th Dalai Lama.",
    images: imgSet("monastery", "attraction", 2),
    videoIds: [],
    durationHours: 1,
    distanceKm: 5,
    travelTime: "20 min",
    bestTime: "Morning",
    difficulty: "easy",
    accessible: "partial",
    permitRequired: false,
    facts: ["Birthplace of the 6th Dalai Lama"],
    nearby: ["place_monastery"],
    sourceIds: ["ap_tourism", "publication"],
    confidence: 0.83,
    routeOrder: 12,
  },
  {
    id: "place_bumla",
    canonicalName: "Bum La Pass",
    altNames: ["Bumla", "Bum La"],
    category: "adventure",
    blurb: "A dramatic border pass at ~15,200 ft. Permit required.",
    description:
      "One of the highest motorable passes near the India–China border. The drive is the experience: switchbacks, snow patches and stark high-altitude scenery. A special permit and local vehicle are required.",
    images: [img("himalaya", "landscape"), img("road", "road"), img("himalaya", "guest", "guest")],
    videoIds: ["vid_1"],
    durationHours: 6,
    distanceKm: 37,
    travelTime: "2.5–3 hrs each way",
    bestTime: "Late morning, weather permitting",
    difficulty: "hard",
    accessible: "no",
    permitRequired: true,
    facts: ["~15,200 ft", "Special permit required", "Local vehicle mandatory"],
    nearby: ["place_madhuri"],
    sourceIds: ["ilp_portal", "ap_tourism", "forum"],
    confidence: 0.88,
    routeOrder: 20,
  },
  {
    id: "place_madhuri",
    canonicalName: "Madhuri Lake",
    altNames: ["Sangetsar Lake", "Sangestar Tso"],
    category: "adventure",
    blurb: "A high-altitude lake ringed by tree stumps and peaks.",
    description:
      "Formed after a 1970s earthquake, this striking lake (locally Sangetsar Tso) sits en route toward the border zone. Permit required; often combined with Bum La.",
    images: [img("lake", "landscape"), img("lake", "guest", "guest")],
    videoIds: ["vid_4"],
    durationHours: 2,
    distanceKm: 32,
    travelTime: "2–2.5 hrs each way",
    bestTime: "Midday",
    difficulty: "moderate",
    accessible: "no",
    permitRequired: true,
    facts: ["Formed after a 1973 earthquake", "Permit required"],
    nearby: ["place_bumla"],
    sourceIds: ["ap_tourism", "publication", "review_platform"],
    confidence: 0.86,
    routeOrder: 21,
  },
  {
    id: "place_sela",
    canonicalName: "Sela Pass",
    altNames: ["Se La"],
    category: "adventure",
    blurb: "A snowbound gateway pass at ~13,700 ft with a sacred lake.",
    description:
      "The high pass connecting Dirang and Tawang, with the frozen-in-winter Sela Lake beside the road. A defining stop on the drive in and out.",
    images: [img("himalaya", "landscape"), img("road", "road")],
    videoIds: ["vid_3"],
    durationHours: 1,
    distanceKm: 78,
    travelTime: "On the route in",
    bestTime: "Late morning",
    difficulty: "moderate",
    accessible: "partial",
    permitRequired: false,
    facts: ["~13,700 ft", "Sela Lake beside the road"],
    nearby: ["place_jaswant", "place_nuranang"],
    sourceIds: ["ap_tourism", "blog"],
    confidence: 0.87,
    routeOrder: 5,
  },
  {
    id: "place_nuranang",
    canonicalName: "Nuranang Falls",
    altNames: ["Jang Falls", "Bong Bong Falls"],
    category: "enroute",
    blurb: "A powerful 100 m waterfall near Jang.",
    description:
      "A dramatic multi-tier waterfall a short detour off the main road near Jang — a popular stop between Sela and Tawang.",
    images: [img("waterfall", "attraction"), img("waterfall", "guest", "guest")],
    videoIds: ["vid_5"],
    durationHours: 1,
    distanceKm: 40,
    travelTime: "On the route in",
    bestTime: "Post-monsoon for volume",
    difficulty: "moderate",
    accessible: "partial",
    permitRequired: false,
    facts: ["~100 m drop", "Featured in Indian cinema"],
    nearby: ["place_sela", "place_jaswant"],
    sourceIds: ["ap_tourism", "publication"],
    confidence: 0.84,
    routeOrder: 6,
  },
  {
    id: "place_jaswant",
    canonicalName: "Jaswant Garh War Memorial",
    altNames: ["Jaswantgarh"],
    category: "enroute",
    blurb: "A moving memorial to a 1962 war hero on the route.",
    description:
      "A memorial maintained by the army honoring Rifleman Jaswant Singh Rawat. Warm tea is often served to travelers; a reflective en-route stop.",
    images: imgSet("himalaya", "attraction", 2),
    videoIds: [],
    durationHours: 0.5,
    distanceKm: 55,
    travelTime: "On the route in",
    bestTime: "Any",
    difficulty: "easy",
    accessible: "yes",
    permitRequired: false,
    facts: ["Honors a 1962 war hero", "Free tea served by the army"],
    nearby: ["place_sela"],
    sourceIds: ["ap_tourism"],
    confidence: 0.82,
    routeOrder: 7,
  },
  {
    id: "place_dirang",
    canonicalName: "Dirang",
    altNames: ["Dirang Valley"],
    category: "enroute",
    blurb: "A gentle valley town — a natural overnight stop.",
    description:
      "A relaxed valley with orchards, hot springs and a historic dzong. The usual acclimatization halt on the drive up to Tawang.",
    images: [img("town", "landscape"), img("himalaya", "landscape")],
    videoIds: [],
    durationHours: 3,
    distanceKm: 137,
    travelTime: "Overnight halt",
    bestTime: "Evening",
    difficulty: "easy",
    accessible: "yes",
    permitRequired: false,
    facts: ["Hot springs nearby", "Historic Dirang Dzong"],
    nearby: ["place_bomdila"],
    sourceIds: ["ap_tourism", "blog"],
    confidence: 0.8,
    routeOrder: 3,
  },
  {
    id: "place_bomdila",
    canonicalName: "Bomdila",
    altNames: ["Bomdila town"],
    category: "enroute",
    blurb: "A ridge town with monastery and mountain views.",
    description:
      "A pleasant town on the way with a Buddhist monastery and viewpoints over the eastern Himalaya. A common first-night halt from Guwahati.",
    images: imgSet("town", "landscape", 2),
    videoIds: [],
    durationHours: 2,
    distanceKm: 180,
    travelTime: "Overnight halt",
    bestTime: "Morning views",
    difficulty: "easy",
    accessible: "yes",
    permitRequired: false,
    facts: ["Bomdila Monastery", "Apple orchards"],
    nearby: ["place_dirang"],
    sourceIds: ["ap_tourism"],
    confidence: 0.79,
    routeOrder: 2,
  },
];

// ---------------------------------------------------------------------------
// HOTELS
// ---------------------------------------------------------------------------
export const TAWANG_HOTELS: HotelOption[] = [
  {
    id: "hotel_h1",
    name: "Snow Ridge Retreat",
    location: "Tawang town, 700 m from Monastery",
    room: "Deluxe mountain-view double",
    pricePerNight: 2850,
    images: [img("hotelroom", "room", "official"), img("bathroom", "bathroom", "guest"), img("town", "exterior", "official")],
    videoIds: ["vid_7", "vid_8"],
    cleanliness: 9.0,
    bathroomScore: 8.6,
    reviewIntelId: "ri_h1",
    policies: ["Free cancellation up to 48h", "Breakfast included", "Heater on request"],
    amenities: ["Room heater", "Hot water", "Restaurant", "Parking"],
    hasElevator: false,
    sourceIds: ["hotel_official", "booking_platform", "review_platform"],
    whyReasons: [
      "Fits your budget",
      "Strong cleanliness evidence (9.0/10)",
      "Bathroom quality 8.6/10",
      "Good recent reviews",
      "700 m from the Monastery",
    ],
    confidence: 0.91,
  },
  {
    id: "hotel_h2",
    name: "Gonpa View Boutique",
    location: "North ridge, 2.1 km from town center",
    room: "Premium king with valley view",
    pricePerNight: 3950,
    images: [img("hotelroom", "room", "official"), img("bathroom", "bathroom", "official")],
    videoIds: [],
    cleanliness: 9.3,
    bathroomScore: 9.0,
    reviewIntelId: "ri_h2",
    policies: ["Free cancellation up to 72h", "Breakfast included", "24h hot water (claimed)"],
    amenities: ["Reliable hot water", "In-room heating", "Cafe", "Airport transfer desk"],
    hasElevator: true,
    sourceIds: ["hotel_official", "booking_platform", "review_platform"],
    whyReasons: [
      "Best bathroom & cleanliness scores",
      "Reliable hot water in reviews",
      "Quietest of the shortlist",
      "Has an elevator (accessibility)",
    ],
    confidence: 0.88,
  },
  {
    id: "hotel_h3",
    name: "Old Town Inn",
    location: "Central bazaar, 300 m from Monastery",
    room: "Standard double",
    pricePerNight: 1750,
    images: [img("hotelroom", "room", "guest"), img("bathroom", "bathroom", "guest")],
    videoIds: [],
    cleanliness: 7.6,
    bathroomScore: 6.8,
    reviewIntelId: "ri_h3",
    policies: ["No free cancellation", "Breakfast extra"],
    amenities: ["Central location", "Hot water (limited hours)", "Cafe nearby"],
    hasElevator: false,
    sourceIds: ["booking_platform", "review_platform", "forum"],
    whyReasons: ["Cheapest central option", "Excellent location", "Friendly owner"],
    confidence: 0.76,
  },
];

// ---------------------------------------------------------------------------
// FLIGHTS (Hyderabad → Guwahati, the gateway airport)
// ---------------------------------------------------------------------------
export const TAWANG_FLIGHTS: FlightOption[] = [
  {
    id: "flight_out_econ",
    airline: "IndiGo",
    flightNo: "6E-6112",
    from: "Hyderabad (HYD)",
    to: "Guwahati (GAU)",
    depart: "08:40",
    arrive: "13:25",
    layover: "1 stop · Kolkata · 55m",
    baggage: "15 kg check-in · 7 kg cabin",
    fare: 6600,
    sourceId: "indigo",
    earlyMorning: false,
    duration: "4h 45m",
    stops: 1,
    stopDetail: "via Kolkata (55m)",
    cabin: "Economy",
    refundable: false,
    onTime: 84,
  },
  {
    id: "flight_out_cheap",
    airline: "Air carrier",
    flightNo: "AA-431",
    from: "Hyderabad (HYD)",
    to: "Guwahati (GAU)",
    depart: "05:15",
    arrive: "10:05",
    layover: "1 stop · Kolkata · 40m",
    baggage: "15 kg check-in · 7 kg cabin",
    fare: 5400,
    sourceId: "airasia",
    earlyMorning: true,
  },
  {
    id: "flight_ret_econ",
    airline: "IndiGo",
    flightNo: "6E-6220",
    from: "Guwahati (GAU)",
    to: "Hyderabad (HYD)",
    depart: "14:10",
    arrive: "18:55",
    layover: "1 stop · Kolkata · 50m",
    baggage: "15 kg check-in · 7 kg cabin",
    fare: 6600,
    sourceId: "indigo",
    earlyMorning: false,
  },
];

// ---------------------------------------------------------------------------
// TRANSPORT (ground legs)
// ---------------------------------------------------------------------------
export const TAWANG_TRANSPORT: TransportOption[] = [
  {
    id: "tr_gau_dirang",
    vehicle: "Innova Crysta (shared/private)",
    operator: "Eastern Himalaya Cabs",
    fromPlace: "Guwahati",
    toPlace: "Dirang",
    price: 9000,
    travelTime: "8–9 hrs",
    scenic: true,
    rating: 4.4,
    images: imgSet("vehicle", "road", 1),
    sourceIds: ["transport_op", "review_platform"],
  },
  {
    id: "tr_dirang_tawang",
    vehicle: "Innova Crysta (private)",
    operator: "Eastern Himalaya Cabs",
    fromPlace: "Dirang",
    toPlace: "Tawang",
    price: 7000,
    travelTime: "5–6 hrs via Sela",
    scenic: true,
    rating: 4.5,
    images: imgSet("road", "road", 1),
    sourceIds: ["transport_op"],
  },
  {
    id: "tr_local_bumla",
    vehicle: "Local permitted 4x4",
    operator: "Tawang Taxi Union",
    fromPlace: "Tawang",
    toPlace: "Bum La & Madhuri Lake",
    price: 6500,
    travelTime: "Full day",
    scenic: true,
    rating: 4.2,
    images: imgSet("vehicle", "road", 1),
    sourceIds: ["transport_op", "forum"],
  },
  {
    id: "tr_tawang_gau",
    vehicle: "Innova Crysta (private)",
    operator: "Eastern Himalaya Cabs",
    fromPlace: "Tawang",
    toPlace: "Guwahati",
    price: 15000,
    travelTime: "12–13 hrs (or split)",
    scenic: true,
    rating: 4.3,
    images: imgSet("road", "road", 1),
    sourceIds: ["transport_op"],
  },
];

// ---------------------------------------------------------------------------
// PERMITS
// ---------------------------------------------------------------------------
export const TAWANG_PERMITS: Permit[] = [
  {
    id: "permit_ilp",
    name: "Inner Line Permit (ILP)",
    requirement: "Required for all non-locals entering Arunachal Pradesh",
    status: "required",
    estimatedCost: 100,
    process: "Apply online via the govt portal; carry a printout + ID.",
    responsible: "Traveler (Gatekeeper can pre-fill)",
    sourceIds: ["ilp_portal"],
  },
  {
    id: "permit_bumla",
    name: "Bum La / Border zone permit",
    requirement: "Separate permit arranged in Tawang for the border sector",
    status: "pending",
    estimatedCost: 2000,
    process: "Arranged locally via DC office / taxi union, usually 1 day prior.",
    responsible: "Local operator",
    sourceIds: ["ilp_portal", "forum"],
  },
];

// ---------------------------------------------------------------------------
// FOOD
// ---------------------------------------------------------------------------
export const TAWANG_FOOD: FoodPick[] = [
  {
    id: "food_f1",
    name: "Dragon Kitchen",
    cuisine: "Tibetan / Momos & Thukpa",
    priceRange: "₹ (budget)",
    location: "Tawang bazaar",
    images: imgSet("food", "food", 2),
    reviewIntelId: "ri_f1",
    whyRecommended: "Consistently praised thukpa, cheap, generous portions.",
  },
  {
    id: "food_f2",
    name: "Orange Restaurant",
    cuisine: "Indian / Chinese",
    priceRange: "₹₹",
    location: "Old Market",
    images: imgSet("food", "food", 1),
    whyRecommended: "Reliable veg/non-veg thalis; warm indoor seating.",
  },
];

export const TAWANG_META = {
  id: "dest_tawang",
  name: "Tawang",
  tagline: "Mountains, monasteries, high-altitude roads and some spectacular Himalayan scenery.",
  region: "Arunachal Pradesh, India",
  gateway: "Guwahati (GAU)",
  hero: img("himalaya", "landscape").url,
  bestSeason: "March–May & September–October",
  facts: [
    "Sits at ~3,000 m altitude",
    "Requires an Inner Line Permit",
    "2 full driving days from Guwahati",
  ],
  now: now(),
  daysAgo,
};
